{% set name = "figanos" %}
{% set version = "0.5.0" %}
{% python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/figanos-{{ version }}.tar.gz
  sha256: 95c0869bf361d56ba86bf3e2ff24770e11edcfd89bb90d34ee81f28aba8c7fda

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.10.1,<4
    - pip
  run:
    - python >={{ python_min }}
    - cartopy >=0.23.0
    - cairosvg >=2.6.0
    - geopandas >=1.0
    - matplotlib-base >=3.6.0
    - numpy >=1.25.0
    - pandas >=2.2.0
    - pint >=0.18
    - platformdirs >=4.0
    - pyyaml >=6.0.1
    - seaborn >=0.13.0
    - scikit-image >=0.21.0
    - xarray >=2023.11.0
    - xclim >=0.52.2

test:
  imports:
    - figanos
  requires:
    - python {{ python_min }}
    - pytest >=8.3.2
    - pip
  source_files:
    - src/figanos
    - tests
  commands:
    - pip check
    - python -m pytest tests

about:
  home: https://github.com/Ouranosinc/figanos
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Tools for producing informative graphics on the impacts of climate change.
  doc_url: https://figanos.readthedocs.io/
  dev_url: https://github.com/Ouranosinc/figanos

extra:
  recipe-maintainers:
    - juliettelavoie
    - sarahclaude
    - Zeitsperre
